import Helpers from '../utilities/Helpers';
import Colors from '../constants/Colors';

export default {
  initialPost: {
    text: "Welcome.\nPlease put your satirical hat on.",
    description: "What if the content transparently conveyed the design-intentions which they embodied?",
  },
  initialUser: {
    name: 'slvtrs', 
    color: Colors.brand,
    story: true,
  },
  profileUser: {
    name: 'Ego',
    color: Helpers.randomColor(),
    story: true,
    bio: "A byproduct of my formative environment experiencing the illusion of free-identity, filtered through a corporate agenda under the guise of \"personal branding.\" ✌️",
  },
  likePrefixes: [
    '',
    '',
    'pity',
    'horny',
    'genuine',
    'confused',
    'envious',
    'obligatory',
    'bot',
    'paid',
    'hashtag',
    'comedic',
    'accidental',
    'ironic',
    'insecure',
  ],
  users: [
    {name: 'filltheholethatismysoul', color: Helpers.randomColor(), story: Math.random() <= 0.75, },
    {name: 'LovingLurker', color: Helpers.randomColor(), story: Math.random() <= 0.75, },
    {name: 'FU.FME!', color: Helpers.randomColor(), story: Math.random() <= 0.75, },
    {name: 'no1fan', color: Helpers.randomColor(), story: Math.random() <= 0.75, },
    {name: 'IdentityThief', color: Helpers.randomColor(), story: Math.random() <= 0.75, },
    {name: 'middleChild', color: Helpers.randomColor(), story: Math.random() <= 0.75, },
    {name: 'instaddict', color: Helpers.randomColor(), story: Math.random() <= 0.75, },
    {name: 'BrownBananas', color: Helpers.randomColor(), story: Math.random() <= 0.75, },
    {name: 'Jesus.H.Christ', color: Helpers.randomColor(), story: Math.random() <= 0.75, },
    {name: 'TheRealGandhi', color: Helpers.randomColor(), story: Math.random() <= 0.75, },
    {name: 'paraphraser', color: Helpers.randomColor(), story: Math.random() <= 0.75, },
    {name: 'shamless1', color: Helpers.randomColor(), story: Math.random() <= 0.75, },
    {name: 'Normie', color: Helpers.randomColor(), story: Math.random() <= 0.75, },
    {name: 'BRAND', color: Helpers.randomColor(), story: Math.random() <= 0.75, },
    {name: 'FireHazard', color: Helpers.randomColor(), story: Math.random() <= 0.75, },
    {name: 'Jeff', color: Helpers.randomColor(), story: Math.random() <= 0.75, },
  ],
  profile: [
    {text: "This is absolutely me."},
    {text: "This is entirely me."},
    {text: "This is eternally me."},
    {text: "This is not my dog."},
    {text: "This is all of me."},
    {text: "This is me."},
    {text: "This is not me."},
    {text: "This is the unchanging me."},
    {text: "This is just who I am."},
    {text: "This is authentically me."},
    {text: "This is me, twice."},
    {text: "This is me being me."},
    {text: "This is my stuff."},
    {text: "This is my face."},
    {text: "These are my things."},
    {text: "This is me?"},
    {text: "This is truly me."},
    {text: "This is embarassing me."},
  ],
  discover: [
    {text: "FOR YOU\nYOU\nYOU!"},
    {text: "Everything you see here is what we think about you."},
    {text: "Stop denying it. We know you're into #this."},
    {text: "Colloquial meme."},
    {text: "Some kid doing that thing you do but way better."},
    {text: "YOU WON'T BELIEVE WHAT HAPPENS IF YOU TAP HERE"},
    {text: "They're too young to be doing that."},
    {text: "Boring stuff with dramatic lighting."},
    {text: "They're too old to be doing that."},
    {text: "Your ex!"},
    {text: "Your ex's mom!"},
    {text: "Dog."},
    {text: "Hot single parents in your area!"},
    {text: "Food."},
    {text: "Literal fish on a hook."},
    {text: "i herd u like mudkips?"},
    {text: "This is not an ad."},
    {text: "Is this your sexual orientation?"},
    {text: "Bionicles."},
    {text: "Your friend's secret account you weren't meant to see."},
    {text: "Given your demographic, you must enjoy #this."},
    {text: "That contact in your phone from 6 years ago."},
    {text: "This is not an ad either."},
    {text: "Aliens?"},
  ],
  activity: [
    {text: "spends too much time on here."},
    {text: "liked something that has nothing to do with you."},
    {text: "is at work..."},
    {text: "is supposed to be in a committed relationship."},
    {text: "is into some weird stuff."},
    {text: "follows the coolest people and you should too."},
    {text: "likes their own posts."},
    {text: "enjoys expressing themselves through other's expression of themselves."},
    {text: "seems hungry."},
  ],
  home: [
    // {text: "✨Smile✨\nHere comes some serotonin!😸🐶😂\n~✌️~", description: "", prefix: 'pavlovian'},
    {text: "Now forget about all that other stuff.", description: "The people around you, your pending chores, the work you're procrastinating, improving yourself..."},
    {text: "And enter the \"Feed State.\"", description: "/fēd stāt/\nA compulsive mental state of hollow reptilian indulgence, devoid of immersion or self-awareness. Characterized by increased dopamine levels juxtaposed by mild self-loathing and a nagging longing to end the process."},
    {text: "Naturally, your interactions will be recorded and processed for profiling and manipulation.", description: "But we've all outgrown our Little Brother complex by now, right?", prefix: 'obligatory'},
    {text: "Screencap from someone famous.", description: "I'm a regular person just trying to compete with the Instalympians #trending #likeforlike #unrelatedbuzzword #gamingthesystem", likes: 2, prefix: 'hashtag'},
    {text: "\"Believe that I am authentically and unapologetically living my best life. You are not.\"", description: "#belikeme #yolo #wanderlust", prefix: 'envious'},
    {text: "This is not an ad.", description: "Crowdfunding brings you: The smarter, cleaner, Bluetooth-enabled version of that thing you googled yesterday, for twice the price!", prefix: 'deceived'},
    {text: "Mysterious.", description: "Too cool for this- this thing that I'm doing right now. 👁️‍🗨️🚮🚰"},
    {text: "A sincere moment from a close friend.", description: "I love 5% of you enough to share this with, and 1% enough to make the time to talk in person, so I'll share it with 100% of you."},
    {text: "\"I have feels.\"", description: ""},
    {text: "Your friend is more attractive than you.", description: "Which do you like best? lmk!"},
    {text: "A dog.", description: "", likes: 3928, prefix: 'genuine'},
    {text: "Another dog.", description: "", likes: 4123, prefix: 'genuine'},
    {text: "A puppy.", description: "", likes: 11010, prefix: 'genuine'},
    {text: "Uncomfortably clothed power pose.", description: "I am above you. #grind", prefix: 'insecure'},
    {text: "\"I did something healthy but it lacked instant gratification so be my suppliment?\"", description: "I swear this is my norm."},
    {text: "Innocent fun with a whole lot of skin showing.", description: "Sex appeal without the sleeze!"},
    {text: "Incoherent video from a concert.", description: "What matters is that you know I was there."},
    {text: "Optical illusion.", description: "Whatever you do, don't think about those things you're neglecting."},
    {text: "Artwork!", description: "Now we can both justify this as inspirational \"productivity.\"", prefix: "commiserating"},
  ],
};
